spring:
  application:
    name: shipping-service

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5438/shippingdb}
    username: ${DB_USER:shippinguser}
    password: ${DB_PASSWORD:shippingpass}

  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${JPA_DDL:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      group-id: shipping-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false

server:
  port: ${SERVER_PORT:8087}

jwt:
  secret: ${JWT_SECRET:change-me-change-me-change-me-change-me-please-32chars}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:admin123@localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

order-service:
  base-url: ${ORDER_SERVICE_URL:http://localhost:8085}
